version: '3'
services:
  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./shared:/usr/src/shared
    ports:
      - "5000:3000"
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./shared:/app/shared
    ports:
      - "8100:8100"
    depends_on:
      - app
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./backend/src/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
