FROM node:20
WORKDIR /usr/src/app

# Install global dependencies
RUN npm install -g nodemon typescript ts-node

# Copy package.json and package-lock.json
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the project files
COPY . .

# Expose the application port
EXPOSE 3000

# Start the application with nodemon and TypeScript
CMD ["nodemon", "--exec", "ts-node src/app.ts"]
